version: '3'

services:

  nextcloud-db:
    image: tobi312/rpi-mariadb:10.3
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - /containers/cloud/mariadb:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: rasproot
      MYSQL_PASSWORD: 4jh4k3
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

    nextcloud:
      image: nextcloud
      container_name: nextcloud
      restart: unless-stopped
      ports:
        - 8080:80
      depends_on:
        - nextcloud-db
      volumes:
        - /containers/cloud/nextcloud/apps:/var/www/html/apps
        - /containers/cloud/nextcloud/config:/var/www/html/config
        - /containers/cloud/nextcloud/data:/var/www/html/data
